// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SosyalYardimApi.Data;

#nullable disable

namespace SosyalYardimApi.Migrations
{
    [DbContext(typeof(SosyalYardimContext))]
    partial class SosyalYardimContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YourNamespace.Models.SosyalYardim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MusteriAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeAck")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OdemeKd")
                        .HasColumnType("int");

                    b.Property<DateTime>("OdemeTr")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OdenecekTtr")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SosyalYardimlar");
                });
#pragma warning restore 612, 618
        }
    }
}
